
import java.awt.Image;
import java.awt.Rectangle;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mehedi H Shovon
 */
public class create extends javax.swing.JFrame {

    /**
     * Creates new form create
     */
    public create() {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(529, 435));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("User");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(38, 22, 90, 14);
        jPanel2.add(jTextField1);
        jTextField1.setBounds(143, 9, 198, 30);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("ID");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(38, 60, 90, 14);
        jPanel2.add(jTextField2);
        jTextField2.setBounds(143, 47, 198, 30);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Email");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(38, 98, 90, 14);
        jPanel2.add(jTextField3);
        jTextField3.setBounds(143, 85, 198, 30);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Contact");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(38, 136, 90, 14);
        jPanel2.add(jTextField4);
        jTextField4.setBounds(143, 123, 198, 30);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Gender");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(38, 175, 90, 14);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Male");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton1);
        jRadioButton1.setBounds(143, 171, 70, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Female");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton2);
        jRadioButton2.setBounds(210, 170, 90, 23);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Date of Birth");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(38, 215, 90, 14);
        jPanel2.add(jTextField5);
        jTextField5.setBounds(143, 212, 198, 30);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Your password needs :::");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(143, 250, 164, 14);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Password");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(38, 250, 90, 14);

        jLabel10.setForeground(new java.awt.Color(0, 51, 255));
        jLabel10.setText("# To be at least 8 characters in length");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(130, 270, 200, 14);
        jPanel2.add(jPasswordField1);
        jPasswordField1.setBounds(142, 290, 199, 30);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("DD / MM / YYYY");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(143, 197, 198, 14);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sream.jpg"))); // NOI18N
        jPanel2.add(jLabel15);
        jLabel15.setBounds(0, 0, 350, 330);

        jLabel17.setText("jLabel17");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(0, 0, 350, 330);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(18, 58, 350, 330);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(null);

        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(24, 13, 65, 23);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(24, 47, 65, 23);

        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(24, 77, 65, 23);
        jPanel3.add(jLabel16);
        jLabel16.setBounds(0, 0, 110, 110);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sream.jpg"))); // NOI18N
        jLabel18.setText("jLabel18");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(0, 0, 110, 110);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(389, 299, 110, 110);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Create Account");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(170, 10, 160, 22);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(null);
        jPanel4.add(jLabel12);
        jLabel12.setBounds(0, 0, 120, 120);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(400, 60, 115, 120);

        jButton4.setText("Get");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(420, 190, 70, 23);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Add Photo");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(400, 30, 110, 20);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sream.jpg"))); // NOI18N
        jLabel14.setText("jLabel14");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(0, 0, 530, 420);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-4, 1, 530, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(WIDTH);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        login l=new login();
        l.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jTextField1.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please Enter User","Error", JOptionPane.ERROR_MESSAGE);
           flag1=1;
           return;
        }
        if (jTextField2.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please Enter ID","Error", JOptionPane.ERROR_MESSAGE);
           flag1=1;
           return;
        }
        if (jTextField3.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please Enter Email","Error", JOptionPane.ERROR_MESSAGE);
           flag1=1;
           return;
        }
        if (jTextField4.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please Enter Contact","Error", JOptionPane.ERROR_MESSAGE);
           flag1=1;
           return;
        }
        if (jTextField5.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please Enter Date of Birth","Error", JOptionPane.ERROR_MESSAGE);
           flag1=1;
           return;
           
        }
       
         if(jPasswordField1.getText().length()<8)
          {
           JOptionPane.showMessageDialog(null,"Password Must Be In 8 Characters");
           flag1=1;
          }
       user=jTextField1.getText();
       id=jTextField2.getText();
       email=jTextField3.getText();
       contact=jTextField4.getText();
       birth=jTextField5.getText();
       //dateofbirth=jTextField5.getText();
       //dateofbirth=jTextField6.getText();
       //gender=jRadioButton1.getText();
       //gender=jRadioButton2.getText();
       password=jPasswordField1.getText();
       //repeatpassword=jPasswordField2.getText();
       ResultSet rs=null;
       PreparedStatement ps=null;
       String query=new String();
      if(flag1==0)
       {
       try{
          query="Insert into scream values('"+user+"','"+id+"','"+email+"','"+contact+"','"+gender+"','"+birth+"','"+password+"')";  
          ps=conn.prepareStatement(query);
          ps.execute();
          JOptionPane.showMessageDialog(null,"Data Inserted Successfully");
          //this.setVisible(false);
          //login l=new login();
          //l.setVisible(true);
          }
       catch(Exception e){
          JOptionPane.showMessageDialog(null,e);
      }
       }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conn = Sqlite.ConnectDB();
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        gender="male";
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        gender="female";
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    JFileChooser c=new JFileChooser();
        c.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int r=c.showOpenDialog(create.this);
        if (r==JFileChooser.APPROVE_OPTION){
            File f=c.getSelectedFile();
            ImageIcon i=new ImageIcon(f.getAbsolutePath());
            Rectangle re=jLabel12.getBounds();
            Image scaledimage =i.getImage().getScaledInstance(re.width, re.height,Image.SCALE_DEFAULT);
            i=new ImageIcon(scaledimage);
            jLabel12.setIcon(i);
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    /*shovon*/
    public static int flag=0;
    public static int flag1=0;
    public Connection conn=null;
    ResultSet rs;
    public static String user=new String();
    public static String id=new String();
    public static String email=new String();
    //public static String repeatemail=new String();
    public static String contact=new String();
    public static String birth=new String();
    public static String gender=new String();
    public static String password=new String();
    /*shovon*/
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new create().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
