/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.ImageIcon;
/**
 *
 * @author Beautiful
 */
public class silent_scream extends javax.swing.JFrame {
    

    /**
     * Creates new form silent_scream
     */
    public silent_scream() 
    {
        initComponents();
                }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel8 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jButton4 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 153));
        setMinimumSize(new java.awt.Dimension(851, 490));
        setPreferredSize(new java.awt.Dimension(851, 490));

        jPanel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setLayout(null);

        jTabbedPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N

        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 204));
        jLabel1.setText("Well Come To Our Library");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(197, 20, 230, 25);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sream.jpg"))); // NOI18N
        jLabel22.setText("jLabel22");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(0, 0, 660, 360);

        jTabbedPane2.addTab("Home", jPanel2);

        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(0, 0, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jButton1);
        jButton1.setBounds(560, 70, 80, 21);

        jTextField1.setBackground(new java.awt.Color(0, 0, 51));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField1);
        jTextField1.setBounds(500, 30, 140, 26);

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel28.setText("Book Name");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(430, 40, 70, 14);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sream.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, -30, 680, 400);

        jTabbedPane2.addTab("Books", jPanel1);

        jPanel3.setLayout(null);
        jPanel3.add(jTextField2);
        jTextField2.setBounds(500, 30, 130, 30);

        jButton2.setText("Search");
        jPanel3.add(jButton2);
        jButton2.setBounds(540, 70, 90, 23);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Magazine Title");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(414, 40, 80, 14);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sream.jpg"))); // NOI18N
        jLabel23.setText("jLabel23");
        jPanel3.add(jLabel23);
        jLabel23.setBounds(0, 0, 660, 360);

        jTabbedPane2.addTab("Magazine", jPanel3);

        jPanel4.setLayout(null);

        jLabel9.setForeground(new java.awt.Color(204, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Select Catargory");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(400, 40, 110, 14);

        jTextField3.setForeground(new java.awt.Color(204, 255, 255));
        jPanel4.add(jTextField3);
        jTextField3.setBounds(510, 30, 129, 28);

        jButton3.setForeground(new java.awt.Color(204, 255, 255));
        jButton3.setText("Search");
        jPanel4.add(jButton3);
        jButton3.setBounds(540, 70, 95, 23);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sream.jpg"))); // NOI18N
        jLabel24.setText("jLabel24");
        jPanel4.add(jLabel24);
        jLabel24.setBounds(0, 0, 660, 360);

        jTabbedPane2.addTab("Newspaper", jPanel4);

        jPanel5.setLayout(null);

        jLabel18.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 204));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("-You must be a member to borrow books from our library");
        jPanel5.add(jLabel18);
        jLabel18.setBounds(140, 60, 460, 25);

        jLabel19.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 204));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("-You can pick up a book for the highest in 15 days");
        jPanel5.add(jLabel19);
        jLabel19.setBounds(190, 97, 410, 25);

        jLabel20.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 204));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("-If more than 15 days , however, a fine of 50Taka per day for");
        jPanel5.add(jLabel20);
        jLabel20.setBounds(130, 134, 470, 25);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sream.jpg"))); // NOI18N
        jLabel25.setText("jLabel25");
        jPanel5.add(jLabel25);
        jLabel25.setBounds(0, 0, 660, 360);

        jTabbedPane2.addTab("Our Rules", jPanel5);

        jPanel6.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 255, 255));
        jLabel12.setText("-shovon96.mh@gmail.com");
        jPanel6.add(jLabel12);
        jLabel12.setBounds(423, 145, 165, 24);

        jLabel13.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 255, 255));
        jLabel13.setText("-01751774932");
        jPanel6.add(jLabel13);
        jLabel13.setBounds(504, 187, 84, 19);

        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 255, 255));
        jLabel14.setText("-University Of Asia Pasific");
        jPanel6.add(jLabel14);
        jLabel14.setBounds(431, 71, 157, 19);

        jLabel15.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 255, 255));
        jLabel15.setText("-MH Shovon");
        jPanel6.add(jLabel15);
        jLabel15.setBounds(509, 34, 79, 19);

        jLabel16.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 255, 255));
        jLabel16.setText("-74/A Green Road");
        jPanel6.add(jLabel16);
        jLabel16.setBounds(475, 108, 113, 19);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sream.jpg"))); // NOI18N
        jLabel26.setText("jLabel26");
        jPanel6.add(jLabel26);
        jLabel26.setBounds(0, 0, 660, 360);

        jTabbedPane2.addTab("Contact", jPanel6);

        jPanel7.setLayout(null);

        buttonGroup1.add(jCheckBox1);
        jCheckBox1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(204, 255, 255));
        jCheckBox1.setText("Most Helpfully");
        jPanel7.add(jCheckBox1);
        jCheckBox1.setBounds(464, 54, 115, 27);

        buttonGroup1.add(jCheckBox2);
        jCheckBox2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(204, 255, 255));
        jCheckBox2.setText("Helpfully");
        jPanel7.add(jCheckBox2);
        jCheckBox2.setBounds(498, 99, 81, 27);

        buttonGroup1.add(jCheckBox3);
        jCheckBox3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(204, 255, 255));
        jCheckBox3.setText("Most Harmfully");
        jPanel7.add(jCheckBox3);
        jCheckBox3.setBounds(458, 144, 121, 27);

        buttonGroup1.add(jCheckBox4);
        jCheckBox4.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jCheckBox4.setForeground(new java.awt.Color(204, 255, 255));
        jCheckBox4.setText("Harmfully");
        jPanel7.add(jCheckBox4);
        jCheckBox4.setBounds(492, 189, 87, 27);

        jButton4.setBackground(new java.awt.Color(0, 51, 153));
        jButton4.setForeground(new java.awt.Color(204, 255, 255));
        jButton4.setText("Done");
        jPanel7.add(jButton4);
        jButton4.setBounds(507, 244, 72, 23);

        jLabel17.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 255, 255));
        jLabel17.setText("Share Your Comment");
        jPanel7.add(jLabel17);
        jLabel17.setBounds(107, 54, 170, 25);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel7.add(jScrollPane1);
        jScrollPane1.setBounds(34, 84, 346, 151);

        jButton5.setBackground(new java.awt.Color(0, 51, 153));
        jButton5.setForeground(new java.awt.Color(204, 255, 255));
        jButton5.setText("Submit");
        jPanel7.add(jButton5);
        jButton5.setBounds(308, 253, 72, 23);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sream.jpg"))); // NOI18N
        jLabel27.setText("jLabel27");
        jPanel7.add(jLabel27);
        jLabel27.setBounds(0, 0, 660, 360);

        jTabbedPane2.addTab("Comment", jPanel7);

        jPanel8.add(jTabbedPane2);
        jTabbedPane2.setBounds(90, 20, 671, 390);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sream.jpg"))); // NOI18N
        jLabel21.setText("jLabel21");
        jPanel8.add(jLabel21);
        jLabel21.setBounds(0, 0, 850, 440);

        jMenu1.setText("File");

        jMenuItem1.setText("Log Off");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Quite");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("View");

        jMenuItem5.setText("My Info");
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("Help");

        jMenuItem7.setText("Our Feacedbook Page");
        jMenu5.add(jMenuItem7);

        jMenuItem6.setText("About");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 851, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        about a=new about();
        a.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(silent_scream.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(silent_scream.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(silent_scream.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(silent_scream.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new silent_scream().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
